# Generated by Django 4.1.4 on 2022-12-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='auto_increment_id',
            field=models.AutoField(default=1234, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
