# Generated by Django 4.1.4 on 2022-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit', '0002_remove_post_id_post_auto_increment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zz',
            field=models.CharField(default=2222, max_length=255),
            preserve_default=False,
        ),
    ]
