# Generated by Django 4.1.4 on 2022-12-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit', '0003_post_zz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auto_increment_id',
            new_name='id_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='zz',
        ),
    ]
