# Generated by Django 4.1.4 on 2023-02-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit', '0012_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
